# Project
version=1.3.8
group=com.baisylia.modestmining
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Modest Mining
mod_author=baisylia, evanbones
mod_id=modestmining
license=All Rights Reserved
description=A vanilla enhancing mod that aims to enhance the mining and tool systems.
credits=Xaidee, cassiancc, mintynoura
minecraft_version_range=[1.21.1, 1.21.2)

# Parchment
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Dependencies
neoforge_version=21.1.219
reliable_remover_version=2.12.1-1.21.1-neoforge
reliable_recipes_version=3.1.3-1.21.1-neoforge
yacl_version=3.8.2+1.21.1
jei_version=19.27.0.340
emi_version=1.1.24+1.21.1
farmers_delight_version=1.21.1-1.3.2
mixin_version=0.8.5

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
